### PR TITLE
Support zig 0.16, fix igText build failure 

### PR DESCRIPTION
**Pull request by reshen**
## Issue 1
With zig 0.16 (`0.16.0-dev.1484+d0ba6642b` specifically), I'm seeing a missing `igText` in the auto-generated bindings [1]; instead, both `igTextEx` and `igTextExEx` are present. The proposed changes here make us work with both 0.15.2 and 0.16.0-dev by switching to `igTextEx`.

[1] With `0.16.0-dev.1484+d0ba6642b`:

```bash
❯ zig build run
run
└─ run exe demo
   └─ compile exe demo Debug native 1 errors
src\main.zig:66:15: error: root source file struct 'cimgui_all' has no member named 'igText'
        _ = ig.igText("Dear ImGui Version: %s", ig.IMGUI_VERSION);
            ~~^~~~~~~
.zig-cache\o\19ff71992309fceca2889f5c8289c0bd\cimgui_all.zig:1:1: note: struct declared here
const __root = @This();
```

## Issue 2
This problem isn't solved here, but applies to both 0.15.2 and 0.16.0-dev. When enabling docking, I'm seeing an opaque types failure [2]. I don't know what the solution for this one is.

[2] With `0.15.2`

```bash
❯ zig build -Ddocking run
run
└─ run exe demo
   └─ compile exe demo Debug native 1 errors
.zig-cache\o\bbc92ceb91ff817d43e74aa248a5e988\cimgui_all.zig:1927:21: error: opaque types have unknown size and therefore cannot be directly embedded in structs
    BoxSelectState: ImGuiBoxSelectState = @import("std").mem.zeroes(ImGuiBoxSelectState),
                    ^~~~~~~~~~~~~~~~~~~
.zig-cache\o\bbc92ceb91ff817d43e74aa248a5e988\cimgui_all.zig:1437:42: note: opaque declared here
pub const struct_ImGuiBoxSelectState_t = opaque {};
                                         ^~~~~~~~~
referenced by:
    struct_ImGuiContext_t: .zig-cache\o\bbc92ceb91ff817d43e74aa248a5e988\cimgui_all.zig:1714:42
    ImGuiContext: .zig-cache\o\bbc92ceb91ff817d43e74aa248a5e988\cimgui_all.zig:2039:26
    19 reference(s) hidden; use '-freference-trace=21' to see all references
```

---

Finally, thanks for all of your awesome work (sokol, dcimgui, etc); it's deeply appreciated.

### CODE REVIEW

**Comment by floooh** [comment]
I would rather wait a bit whether those problems will be fixed in Zig. Especially the var-args issue with igText looks like a regression in Zig that needs to be fixed on their side.

PS: weird though that the igText binding is completely missing... let me have a look in the dcimgui repo what's going on there... (might be a regression in the translateC step not converting varargs functions).

**Comment by floooh** [comment]
Hmm, zig version `0.16.0-dev.1484+d0ba6642b` appears to work fine here without changes. I tested only on macOS so far though.

What platform are you on?

E.g.:
```
> zig version
0.16.0-dev.1484+d0ba6642b
> git clone https://github.com/floooh/sokol-zig-imgui-sample
> cd sokol-zig-imgui-sample
> zig build run
...compiles and opens window
```
...also works after clearing the global zig cache.

**Comment by reshen** [comment]
> I would rather wait a bit whether those problems will be fixed in Zig. Especially the var-args issue with igText looks like a regression in Zig that needs to be fixed on their side.

Yep, that makes sense.

> Hmm, zig version 0.16.0-dev.1484+d0ba6642b appears to work fine here without changes. I tested only on macOS so far though. What platform are you on?

Ah, that's very interesting. I was having failures on Windows 11, but I just switched to my macbook and sure enough, the `main` branch builds fine. So probably a different sort of regression in 0.16 that's platform specific?

I'm consistently seeing the opaque binding problem (Issue 2 above), but probably fine to close this PR.  Thanks for having a look!

**Comment by floooh** [comment]
I'll keep the PR open but switched it to draft. Eventually I'd like to figure out what's wrong if the problem doesn't "fix itself".

**Comment by floooh** [comment]
I just fixed a similar issue (https://github.com/floooh/dcimgui/issues/9) by removing imgui_internal.h from the dcimgui Zig bindings again (this was pulling in the problematic `ImGuiBoxSelectState` C struct which contains a bitfield which cannot be handled by Zig's translateC.

There are many more problems currently with the latest Zig 0.16 dev version because the old IO code has now been removed. This needs to be fixed in seprata updates.

In any case, I'll close this PR :)
